name: 'Actually publish PR'

on:
  workflow_run:
    workflows: [Publish PRs]
    types:
      - completed

permissions:
  packages: write
  actions: read
  contents: write
  issues: write
  pull-requests: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Upload
        uses: ForgeForce/action-pr-publishing@mainff
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          uploader-workflow-name: 'Publish PRs'
          #artifacts_base_path:
