name: Test PRs

on:
  pull_request:
    types:
      - opened
      - synchronize

permissions:
  contents: read
  statuses: write

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1000
          fetch-tags: true

      - name: Make Gradle executable
        # language=bash
        run: chmod +x ./gradlew # Thanks Windows

      - name: Setup Java 17
        # https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md#java
        # language=bash
        run: export JAVA_HOME=$(echo $JAVA_HOME_17_X64)

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build

      - name: Run compat checks
        uses: gradle/gradle-build-action@v2
        with:
          arguments: checkJarCompatibility

      - uses: actions/upload-artifact@v4
        with:
          name: jcc
          path: jcc.json
